version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: php
    volumes:
      - ./media:/var/www/html/media:rw 
    ports:
      - 80:80
      - 443:443
    depends_on:
      - database
    
  database:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    ports:
    - 3306:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MARIADB_USER=gurveer
      - MARIADB_PASSWORD=gsingh
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=midterm2
